# Generated by Django 4.1.4 on 2022-12-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_alter_messages_options_forum_created_forum_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=200),
        ),
    ]
