# Generated by Django 3.2.7 on 2022-05-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_manna_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='manna',
            name='category',
            field=models.CharField(default='Christian Charge', help_text='e.g Prayer upliftment, Charge on Faith', max_length=30),
        ),
    ]
