# Generated by Django 3.2.7 on 2022-05-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
