# Generated by Django 4.1.4 on 2022-12-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manna",
            name="bible_verses",
            field=models.CharField(
                blank=True,
                help_text="Enter the book of the bible(in full please like Hebrew)",
                max_length=200,
                null=True,
            ),
        ),
    ]
