# Generated by Django 3.2.7 on 2022-05-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manna',
            name='keyverses',
        ),
        migrations.AlterField(
            model_name='manna',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/'),
        ),
    ]
