# Generated by Django 3.2.7 on 2022-05-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_manna_bible_verses'),
    ]

    operations = [
        migrations.AddField(
            model_name='manna',
            name='chapter_of_bible_verse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manna',
            name='verse_of_chapter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manna',
            name='bible_verses',
            field=models.CharField(help_text='Enter the book of the bible', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='manna',
            name='category',
            field=models.CharField(default='Christian Charge', help_text='e.g Prayer charge, Charge on Faith', max_length=30),
        ),
    ]
