# Generated by Django 3.2.7 on 2022-05-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220523_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='manna',
            name='display_verse',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='manna',
            name='bible_verses',
            field=models.CharField(help_text='Enter the book of the bible(in full please like Hebrew)', max_length=200, null=True),
        ),
    ]
