# Generated by Django 3.2.7 on 2022-05-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220523_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manna',
            name='verse_of_chapter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
